label: 'Terme de taxonomie'
description: 'Contenu associé à un terme de taxonomie donné.'
display:
  default:
    display_title: Maître
    display_options:
      exposed_form:
        options:
          submit_button: Appliquer
          reset_button_label: Réinitialiser
          exposed_sorts_label: 'Trier par'
      pager:
        options:
          expose:
            items_per_page_label: 'Éléments par page'
            items_per_page_options_all_label: '- Tout -'
            offset_label: Décalage
      arguments:
        tid:
          exception:
            title: Tout
      fields:
        nothing:
          alter:
            text: "<div class=\"row\">\r\n  <div class=\"col-lg-2 col-md-3 col-sm-3\">\r\n    {{ field_blog_author_image }}\r\n  </div>\r\n  <div class=\"col-lg-10 col-md-9 col-sm-9\">\r\n    <h3 class=\"h4\">{{ title }}</h3>\r\n    <span class=\"pull-right brdr-lft\"><span class=\"glyphicon glyphicon-comment mrgn-lft-md mrgn-rght-md\"></span>Commenter ({{ comment_count }})</span>\r\n    <p>par <strong>{{ field_blog_author }}</strong> dans la catégorie <strong>{{ field_blog_category }}</strong></p>\r\n    <p>{{ created }}</p>\r\n    <p>{{ body }}</p>\r\n    <p>Continuer la lecture \"{{ title }}\"</p>\r\n  </div>\r\n</div>"
  page_2:
    display_options:
      fields:
        nothing:
          alter:
            text: "<div class=\"row\">\r\n  <div class=\"col-lg-2 col-md-3 col-sm-3\">\r\n    {{ field_blog_author_image }}\r\n  </div>\r\n  <div class=\"col-lg-10 col-md-9 col-sm-9\">\r\n    <h3 class=\"h4\">{{ title }}</h3>\r\n    <span class=\"pull-right brdr-lft\"><span class=\"glyphicon glyphicon-comment mrgn-lft-md mrgn-rght-md\"></span>Commenter ({{ comment_count }})</span>\r\n    <p>par <strong>{{ field_blog_author }}</strong> dans la catégorie <strong>{{ field_blog_category }}</strong></p>\r\n    <p>{{ created }}</p>\r\n    <p>{{ body }}</p>\r\n    <p>Continuer la lecture \"{{ title }}\"</p>\r\n  </div>\r\n</div>"
