determine_menu: true
disable_admin_page: true
append_current_page: false
current_page_as_link: false
append_member_page: false
member_page_as_link: false
remove_home: false
add_home: false
home_as_site_name: false
menu_breadcrumb_menus:
  main:
    enabled: 1
    langhandle: 1
    weight: -10
    taxattach: 0
  brand-fr:
    weight: 0
    enabled: 0
    taxattach: 0
    langhandle: 0
  tools:
    weight: 0
    enabled: 0
    taxattach: 0
    langhandle: 0
  toolkit:
    enabled: 1
    weight: 0
    taxattach: 0
    langhandle: 0
  sidebar:
    weight: 0
    enabled: 0
    taxattach: 0
    langhandle: 0
  plans:
    enabled: 0
    weight: 0
    taxattach: 0
    langhandle: 0
  footer-fr:
    weight: 0
    enabled: 0
    taxattach: 0
    langhandle: 0
  mid-term-self-assessment-20:
    weight: 0
    enabled: 0
    taxattach: 0
    langhandle: 0
  admin:
    weight: 0
    enabled: 0
    taxattach: 0
    langhandle: 0
  analytics:
    weight: 0
    enabled: 0
    taxattach: 0
    langhandle: 0
  footer:
    weight: 0
    enabled: 0
    taxattach: 0
    langhandle: 0
  end-term-self-assessment-20:
    weight: 0
    enabled: 0
    taxattach: 0
    langhandle: 0
  devel:
    weight: 0
    enabled: 0
    taxattach: 0
    langhandle: 0
  consultations:
    enabled: 0
    weight: 0
    taxattach: 0
    langhandle: 0
  commitments:
    weight: 0
    enabled: 0
    taxattach: 0
    langhandle: 0
  brand:
    weight: 0
    enabled: 0
    taxattach: 0
    langhandle: 0
  sidebar-fr:
    weight: 0
    enabled: 0
    taxattach: 0
    langhandle: 0
  account:
    weight: 0
    enabled: 0
    taxattach: 0
    langhandle: 0
_core:
  default_config_hash: cQ5PlGtatt2RcAsy3ZvFrnpvCRT-VdbdrFEV-XUpEAI
