id: password_reset_rules
label: 'Password reset rules'
password_reset: 0
langcode: en
policy_constraints: {  }
roles:
  administrator: administrator
  creator: creator
  editor: editor
  reviewer: reviewer
  comment_moderator: comment_moderator
